/** Per-ingredient common measurement suggestions (2-4 per item, sorted by likelihood) */
export const INGREDIENT_MEASUREMENTS: Record<string, string[]> = {
  "chicken breast": ["500g", "1 piece", "200g"],
  "chicken thighs": ["500g", "4 pieces", "300g"],
  "ground beef": ["500g", "250g", "1 lb"],
  "pork belly": ["400g", "500g", "1 lb"],
  "salmon": ["200g", "1 fillet", "400g"],
  "shrimp": ["200g", "300g", "500g"],
  "butter": ["2 tbsp", "100g", "1/4 cup"],
  "flour": ["2 cups", "250g", "1 cup"],
  "sugar": ["1 cup", "200g", "2 tbsp"],
  "olive oil": ["2 tbsp", "1/4 cup", "1 tbsp"],
  "milk": ["1 cup", "250ml", "2 cups"],
  "eggs": ["2 pieces", "3 pieces", "1 piece"],
  "garlic": ["3 cloves", "2 cloves", "1 clove"],
  "onion": ["1 piece", "2 pieces", "1/2 piece"],
  "rice": ["1 cup", "2 cups", "200g"],
  "pasta": ["200g", "100g", "400g"],
  "cream": ["1 cup", "250ml", "2 tbsp"],
  "cheese": ["100g", "1/2 cup", "200g"],
  "tomato": ["2 pieces", "1 piece", "200g"],
  "potato": ["2 pieces", "300g", "1 piece"],
  "carrot": ["2 pieces", "150g", "1 piece"],
  "spinach": ["2 cups", "100g", "1 bunch"],
  "mushrooms": ["200g", "1 cup", "100g"],
  "soy sauce": ["2 tbsp", "3 tbsp", "1 tbsp"],
  "lemon juice": ["2 tbsp", "1 tbsp", "3 tbsp"],
  "honey": ["2 tbsp", "1 tbsp", "3 tbsp"],
  "cornstarch": ["2 tbsp", "1 tbsp", "3 tbsp"],
  "baking powder": ["1 tsp", "2 tsp", "1/2 tsp"],
  "cinnamon": ["1 tsp", "2 tsp", "1/2 tsp"],
  "salt": ["1 tsp", "1/2 tsp", "2 tsp"],
  "pepper": ["1/2 tsp", "1 tsp", "1/4 tsp"],
  "paprika": ["1 tsp", "2 tsp", "1/2 tsp"],
  "cumin": ["1 tsp", "2 tsp", "1/2 tsp"],
  "ginger": ["1 tsp", "1 tbsp", "2 tsp"],
};

/** Fallback measurements shown when no specific ingredient entry matches */
export const FALLBACK_MEASUREMENTS = ["100g", "1 cup", "2 tbsp", "1 piece"];
